# Numpy

In [1]:
import numpy as np

In [9]:
#Creamos un np array de rango 1,
un_array = np.array([[7,77,777],[7,77,777],[7,77,777]])
print(type(un_array))

<class 'numpy.ndarray'>


In [10]:
#imprimimos la forma (shape) del array
print(type(un_array.shape))
print(un_array.shape)
print(un_array)

<class 'tuple'>
(3, 3)
[[  7  77 777]
 [  7  77 777]
 [  7  77 777]]


In [13]:
#accedemos a las variables
print(un_array[0][0])
un_array[2][2] = 4
print(un_array)

7
[[  7  77 777]
 [  7  77 777]
 [  7  77   4]]


## Como crear un array multidimensional

In [15]:
#Igual que de la forma anterior

In [16]:
print("La forma del array es: ",un_array.shape, " - Array bidimensional")

La forma del array es:  (3, 3)  - Array bidimensional


In [17]:
print("Así tambien se accede a un valor en el array de dos dimensiones: ",un_array[2,0])

Así tambien se accede a un valor en el array de dos dimensiones:  7


## Distintas maneras de crear nd arrays

In [18]:
#crear array lleno de ceros
ej1 = np.zeros((1080,1920))
print(ej1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
#creamos un array lleno de un valor determinado (floats por ejemplo)
ej2 = np.full((2,2),9.1)
print(ej2)

[[9.1 9.1]
 [9.1 9.1]]


In [20]:
#creamos un array de axb con diagonal en 1 y resto en 0
ej3 = np.eye(7,7)
print(ej3)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [21]:
#creando un array de 1
ej4 = np.ones((10,7,2)) # en este caso matriz tridimensional
print(ej4)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [22]:
#creamos un array flotantes aleatorios entre 0 y 1
ej5 = np.random.random((5,5))
print(ej5)

[[0.95168527 0.38012841 0.90002942 0.99452764 0.3249772 ]
 [0.14635585 0.98459257 0.34801816 0.40608039 0.4277952 ]
 [0.30783141 0.78122335 0.19382509 0.46630498 0.56567247]
 [0.25923528 0.07327456 0.12001127 0.24804108 0.15580347]
 [0.19778293 0.97672505 0.40303394 0.1105734  0.11253606]]


## Array de índices

In [25]:
array_a = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print(array_a)
print(array_a.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
(4, 3)


In [26]:
#creamos 2 arrays con números enteros que usaremos como indices
cols = np.array([0,1,2,0])
rows = np.arange(4)
print("Indices para filas -> ", rows)
print("Indices para columnas -> ", cols)

Indices para filas ->  [0 1 2 3]
Indices para columnas ->  [0 1 2 0]


In [27]:
#imprimimos los indeices tomando uno de cada array, de a pares
for row,col in zip(rows,cols):
    print("(",row,",",col,")")

( 0 , 0 )
( 1 , 1 )
( 2 , 2 )
( 3 , 0 )


In [28]:
#entonces ahora para seleccional un elemento de cada fila, se realiza de esta manera
print("Los valores contenidos en los indices son: ",array_a[rows,cols])

Los valores contenidos en los indices son:  [11 22 33 41]


In [29]:
#vamos a operar con los valores seleccionados
print(array_a)
array_a[rows,cols]+=1000
print(array_a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
[[1011   12   13]
 [  21 1022   23]
 [  31   32 1033]
 [1041   42   43]]


## Indexado booleano
Indexado booleano para cambiar elementos

In [30]:
# se crea un array de 3x2
array_b = np.array([[11,12],[21,22],[31,32]])
print(array_b)
print("___________")
print(array_b.shape)

[[11 12]
 [21 22]
 [31 32]]
___________
(3, 2)


In [31]:
# se crea un filtro
filtro = (array_b > 15)
filtro

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [32]:
#Se aplica el filtro al array
filtrado = array_b[filtro]
filtrado

array([21, 22, 31, 32])

In [33]:
#se puede aplicar al unisono
print(array_b[(array_b % 2 == 0)])

[12 22 32]


El uso principal de este tipo de filtros es el de poder modificar los valores del array qe cumplan cierto criterio

In [34]:
array_b[array_b % 2 == 0]+= 1000
print(array_b)

[[  11 1012]
 [  21 1022]
 [  31 1032]]


## Rebanando arrays (Slice)
Hacer slice a un array, sirve para aislar una "sub-region" de la matriz de un ndarray

In [2]:
un_array = np.array([[11,12,13,14,15,16],[21,22,23,24,25,26],[31,32,33,34,35,36],[41,42,43,45,45,46]])
print(un_array)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 45 45 46]]


In [3]:
#creamos un slice de 2x2 a partir de un array
un_slice = un_array[:2,1:3] #El numero final de la selección no está incluida, por el contrario el inicio si
print(un_slice)

[[12 13]
 [22 23]]


In [4]:
print("Slice: ",un_slice[0,0]) #Se generan nuevos indices para el nuevo slice

Slice:  12


In [5]:
un_slice[0,0] += 100
print("Slice: ",un_slice[0,0])

Slice:  112


In [6]:
print("Array original: ",un_array[0,1]) #Se imprime la posición (0,1) del array original

Array original:  112


Se realiza un paso por referencia, acceso directo que apunta a la sección de memoria

In [7]:
print(un_array)

[[ 11 112  13  14  15  16]
 [ 21  22  23  24  25  26]
 [ 31  32  33  34  35  36]
 [ 41  42  43  45  45  46]]


In [8]:
nuevo_array = np.array(un_slice) #Se crea un nuevo ndArray, este ya no comparte el mismo espacio de memoria
print(nuevo_array)

[[112  13]
 [ 22  23]]


In [9]:
#Slice
#seleccion de filas y columnas por aparte
row_rank1 = un_slice[1,:]
col_rank1 = un_slice[:,1]
print(row_rank1,row_rank1.shape)
print(col_rank1,col_rank1.shape)

[22 23] (2,)
[13 23] (2,)


## Tipos de datos de los arrays

In [10]:
#en este caso python se encarga de asignar el tipo de datos
ej1 = np.array([11,12])
print(ej1.dtype)

int32


In [11]:
#python asigna el tipo de dato
ej2 = np.array([11.0,12.0])
print(ej2.dtype)

float64


In [12]:
#tambien puedo forzar el tipo de datos expresandlo de manera explicita
ej3 = np.array([11,21], dtype=np.float64)
print(ej3.dtype)

float64


In [13]:
#si se necesitara se podría forzar flotantes a enteros
ej4 = np.array([11.1,12.7], dtype=np.int64)
print(ej4.dtype)
print()
print(ej4)

int64

[11 12]


## Operaciones aritméticas

In [14]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)
print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [15]:
#resta
print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [16]:
#multiplicacion
print(x*y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [17]:
#division
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [18]:
#raiz cuadrada
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


## Operaciones Estadísticas Básicas

In [20]:
#generar un array aleatorio
arr = 10 * np.random.randn(2,5)
print(arr)

[[ -6.68330566  15.17533083 -10.333498     4.84024006 -23.13774636]
 [-15.40674576   7.45931934  -5.32946657  18.62208268  -1.05051244]]


In [21]:
#calcular la media (promedio) de un array
print(arr.mean())

-1.584430188222433


In [22]:
#calcular el promedio pero en este caso, fila por fila
#importante
#eje 0 = columnas
#eje 1 = filas
print(arr.mean(axis=1))

[-4.02779583  0.85893545]


In [23]:
#calcular promedio columna por columna
print(arr.mean(axis=0))

[-11.04502571  11.31732508  -7.83148229  11.73116137 -12.0941294 ]


In [24]:
#se crea un array de 10 elementos aleatorios
desordenado = np.random.randn(10)
print(desordenado)

[-0.7622426   2.41683583  0.40902726 -1.71964433 -0.89336926 -0.88531444
 -1.22843473 -1.90448028 -1.00913101 -0.44609115]


In [25]:
#se crea una copia
ordenado = np.array(desordenado)
#se ordena
ordenado.sort()
print(ordenado)

[-1.90448028 -1.71964433 -1.22843473 -1.00913101 -0.89336926 -0.88531444
 -0.7622426  -0.44609115  0.40902726  2.41683583]


In [26]:
#buscar elementos unicos
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


In [27]:
#Operaciones de conjunto
s1 = np.array(['escritorio','silla','mesa'])
s2 = np.array(['escritorio','silla','lampara'])
print(s1)
print(s2)

['escritorio' 'silla' 'mesa']
['escritorio' 'silla' 'lampara']


In [28]:
#interseccion
print(np.intersect1d(s1,s2))

['escritorio' 'silla']


In [29]:
#union en 1d
print(np.union1d(s1,s2))

['escritorio' 'lampara' 'mesa' 'silla']


In [31]:
#Elementos de s1 que no están en s2
print(np.setdiff1d(s1,s2))

['mesa']


In [32]:
#que elementos de s1 están en s2
print(np.in1d(s1,s2))

[ True  True False]


## Operaciones frecuentes - Speed test

In [35]:
#sumamos todos los elementos de un array
ex1 = np.array([[11,12],[21,22]])
print(np.sum(ex1))

66


In [36]:
#sumamos solo una columna
print(np.sum(ex1,axis=0))
#sumamos solo una fila
print(np.sum(ex1, axis=1))


[32 34]
[23 43]


Formateando un array

In [37]:
#creando un array
arr = np.arange(20)
print(arr)
arr.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


(20,)

In [38]:
#cambiamos su forma
reshped_arr = arr.reshape(4,5)
print(reshped_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [40]:
#Transponer o transposicionar un array
ex1 = np.array([[11,12],[21,22]])
print(ex1)
ex1.T

[[11 12]
 [21 22]]


array([[11, 21],
       [12, 22]])

In [41]:
# WHERE
mat = np.random.rand(4,4)
mat

array([[0.66320212, 0.15070072, 0.15553449, 0.09580984],
       [0.76712324, 0.5937555 , 0.83027751, 0.0601448 ],
       [0.88231921, 0.73629852, 0.00855405, 0.29536781],
       [0.69694568, 0.00852887, 0.60378414, 0.07980998]])

In [42]:
#le paso array condicion, valor si true, valor si false
np.where(mat>0.5,1000,-1)

array([[1000,   -1,   -1,   -1],
       [1000, 1000, 1000,   -1],
       [1000, 1000,   -1,   -1],
       [1000,   -1, 1000,   -1]])

In [44]:
#comprobar si algun elemento del array es verdadero
arr_bools = np.array([0,0,0,0,0,1])
arr_bools.any()

True

In [45]:
#comprobar si todos los elementos del array son True
arr_bools = np.array([1,1,False])
arr_bools.all()

False

Uniendo data sets

In [46]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)
print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[37 18]
 [31 21]]

[[15 43]
 [37 44]]


In [48]:
#unimos "apilando" verticalmente
np.vstack((K,M))

array([[37, 18],
       [31, 21],
       [15, 43],
       [37, 44]])

In [49]:
#unimos "aplilando" horizontalmente
np.hstack((K,M))

array([[37, 18, 15, 43],
       [31, 21, 37, 44]])

In [51]:
np.concatenate([K,M], axis=0)

array([[37, 18],
       [31, 21],
       [15, 43],
       [37, 44]])

In [52]:
np.concatenate([K,M], axis=1)

array([[37, 18, 15, 43],
       [31, 21, 37, 44]])

## Propagación

In [54]:
base = np.zeros((4,4))
print(base)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [55]:
#se crea un array unidimensional
row = np.array([1,0,2,7])
print(row)
print(row.shape)

[1 0 2 7]
(4,)


In [56]:
y = base + row # se propaga la suma a lo largo del array
print(y)

[[1. 0. 2. 7.]
 [1. 0. 2. 7.]
 [1. 0. 2. 7.]
 [1. 0. 2. 7.]]


In [62]:
#repetimos los mismo pero ahora a base se le sumará una columa
col = np.array([[0,1,2,3]])
print(col)

[[0 1 2 3]]


In [63]:
#se necesita verticalizar esta fila
col = col.T
print(col)

[[0]
 [1]
 [2]
 [3]]


In [64]:
y = base + col # de igualmanera se propaga la suma pero a lo ancho
print(y)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [65]:
col = np.array([[0,1,2]])
col = col.T
print(col)

[[0]
 [1]
 [2]]


In [66]:
#que pasa cuando se hace una operación de propagación
y = base + col
print(y)

ValueError: operands could not be broadcast together with shapes (4,4) (3,1) 

In [67]:
arr_x = np.array([1])
print(arr_x)
print("__________")
print(base+arr_x)

[1]
__________
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Prueba de velocidad

In [69]:
from numpy import arange
from timeit import Timer

size = 1000000
timeits = 1000

nd_array = arange(size)
print("tipo de datos -> ",type(nd_array))
print("Forma -> ",nd_array.shape)

tipo de datos ->  <class 'numpy.ndarray'>
Forma ->  (1000000,)


In [70]:
#con la funcion timer podemos medir, el tiempo que lleva realizar una operación o función
timer_numpy = Timer("nd_array.sum()","from __main__ import nd_array")
print("Time taken by numpy ndarray: %f seconds" % (timer_numpy.timeit(timeits)))

Time taken by numpy ndarray: 0.611726 seconds


In [71]:
a_list = list(range(size))
print(type(a_list))
print("Forma -> ",len(a_list))

<class 'list'>
Forma ->  1000000


In [72]:
timer_list = Timer("sum(a_list)","from __main__ import a_list")
print("Time taken by list: %f seconds" % (timer_list.timeit(timeits)))

Time taken by list: 35.705844 seconds


## Grabar array a disco / recuperar array de disco

In [73]:
x = np.array([23.23, 24.24])

In [74]:
np.save('array_importante',x)

In [75]:
recuperado = np.load('array_importante.npy')
print("el array recuperador es: ",recuperado)

el array recuperador es:  [23.23 24.24]
